INSERT INTO product (id, name, price) VALUES (1, 'Very good item', 100);
INSERT INTO product (id, name, price) VALUES (2, 'Very good item 2', 100);
INSERT INTO product (id, name, price) VALUES (3, 'Very good item 3', 100);
INSERT INTO product (id, name, price) VALUES (4, 'Very good item 4', 100);
INSERT INTO product (id, name, price) VALUES (5, 'Very good item 5', 100);
INSERT INTO product (id, name, price) VALUES (6, 'Very good item 6', 100);
INSERT INTO product (id, name, price) VALUES (7, 'Very good item 7', 100);
INSERT INTO product (id, name, price) VALUES (8, 'Very good item 8', 100);
INSERT INTO product (id, name, price) VALUES (9, 'Very good item 9', 100);
INSERT INTO product (id, name, price) VALUES (10, 'Very good item 10', 100);
INSERT INTO product (id, name, price) VALUES (11, 'Very good item 11', 100);
INSERT INTO product (id, name, price) VALUES (12, 'Very good item 12', 100);
INSERT INTO product (id, name, price) VALUES (13, 'Very good item 13', 100);
INSERT INTO product (id, name, price) VALUES (14, 'Tank', 30000000);
INSERT INTO product (id, name, price) VALUES (15, 'Aircraft', 40000000);